@startuml
skinparam classAttributeIconSize 0

Программирование : создание программ, нацеленных на
Программирование : решение тех или иных задач через
Программирование : специальные языки программирования

Императивное : программирование, при котором
Императивное :  главный вопрос "Как сделать?"
Императивное : то есть программируется сам процесс
Императивное : приводящий к конечному результату

Декларативное : программирование, при котором главный
Декларативное : вопрос "Что сделать?", то есть пишется
Декларативное : код на языках, позволяющих описать конечный
Декларативное : результат своим синтаксисом, чтобы сами
Декларативное : языки смогли в последствии полученный
Декларативное : код переработать в результат

Структурное : программирование с определёнными правилами
Структурное : в построении, ведении кода и определёнными
Структурное : последовательсностями

Неструктурное : программирование без определённых правил
Неструктурное : построения кода, с возможными скачками
Неструктурное : и перепрыгиваниями с одной части кода
Неструктурное : на другую, в таком коде могут использовать "go to"

Логичсекое : основанная на математической логике -
Логичсекое : программы в ней задаются в форме
Логичсекое : логических утверждений и правил вывода

Функциональное : процесс вычисления трактуется как вычисление
Функциональное : значений функций в математическом понимании

Аппликативное : написание программы состоит в систематическом
Аппликативное : осуществлении применения одного объекта к другому

Комбинаторное : при объявлении функций не используются
Комбинаторное : промежуточные переменные,
Комбинаторное : но составляются цепочки из функций

Процедурное : последовательно выполняемые операторы
Процедурное : можно собрать в подпрограммы, то
Процедурное : есть более крупные целостные единицы кода,
Процедурное : с помощью механизмов самого языка

Объектно_ориентированное : представлении программы в виде
Объектно_ориентированное : совокупности взаимодействующих
Объектно_ориентированное : объектов, каждый из которых является
Объектно_ориентированное : экземпляром определённого класса,
Объектно_ориентированное : а классы образуют иерархию наследования


На_основе_классов : всё программирование происходит с использованием
На_основе_классов : классов, их методов, функций и, наследования

Прототипное : отсутствует понятие класса, а наследование производится
Прототипное : путём клонирования существующего экземпляра объекта - прототипа


Императивное <- Программирование
Декларативное <- Программирование

Структурное <- Императивное
Неструктурное <- Императивное

Логичсекое <- Декларативное
Функциональное <- Декларативное

Функциональное <.. Структурное
Объектно_ориентированное <- Структурное
Процедурное <- Структурное

Аппликативное <- Функциональное
Комбинаторное <- Функциональное

Прототипное <- Объектно_ориентированное
На_основе_классов <- Объектно_ориентированное

@enduml
